/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.form;

import controller.Controller;
import domain.Bibliotekar;
import domain.Knjiga;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Nikola
 */
public class FKnjiga extends javax.swing.JDialog {

    /**
     * Creates new form FKnjiga
     */
    public FKnjiga() {
        initComponents();
        
        prepareForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtxtNaslov = new javax.swing.JTextField();
        jtxtAutor = new javax.swing.JTextField();
        jtxtIzdavac = new javax.swing.JTextField();
        jtxtISBN = new javax.swing.JTextField();
        jtxtJezik = new javax.swing.JTextField();
        jtxtBrojStrana = new javax.swing.JTextField();
        jtxtUkupanBrojKnjiga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtOpis = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jbtnOtkazi = new javax.swing.JButton();
        errorNaslov = new javax.swing.JLabel();
        errorAutor = new javax.swing.JLabel();
        errorIzdavac = new javax.swing.JLabel();
        errorIsbn = new javax.swing.JLabel();
        errorJezik = new javax.swing.JLabel();
        errorBrojStrana = new javax.swing.JLabel();
        errorUkupanBroj = new javax.swing.JLabel();
        errorOpis = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nova Knjiga"));

        jLabel2.setText("Naslov:");

        jLabel3.setText("Autor:");

        jLabel4.setText("Izdavac:");

        jLabel5.setText("ISBN:");

        jLabel6.setText("Jezik:");

        jLabel7.setText("Broj strana:");

        jLabel8.setText("Ukupan broj primeraka:");

        jLabel9.setText("Opis:");

        jtxtIzdavac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtIzdavacActionPerformed(evt);
            }
        });

        jtxtOpis.setColumns(20);
        jtxtOpis.setRows(5);
        jScrollPane1.setViewportView(jtxtOpis);

        jButton1.setText("Sacuvaj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbtnOtkazi.setText("Otkazi");
        jbtnOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOtkaziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtUkupanBrojKnjiga)
                            .addComponent(jtxtBrojStrana)
                            .addComponent(jtxtJezik)
                            .addComponent(jtxtISBN)
                            .addComponent(jtxtIzdavac)
                            .addComponent(jtxtAutor)
                            .addComponent(jtxtNaslov))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errorNaslov)
                            .addComponent(errorAutor)
                            .addComponent(errorIzdavac)
                            .addComponent(errorIsbn)
                            .addComponent(errorJezik)
                            .addComponent(errorBrojStrana)
                            .addComponent(errorUkupanBroj)
                            .addComponent(errorOpis))
                        .addGap(146, 146, 146))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(jbtnOtkazi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxtNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(errorNaslov)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(errorAutor)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxtIzdavac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(errorIzdavac)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorIsbn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxtJezik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(errorJezik)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxtBrojStrana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(errorBrojStrana)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxtUkupanBrojKnjiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(errorUkupanBroj)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorOpis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnOtkazi)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtIzdavacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtIzdavacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtIzdavacActionPerformed

    private void jbtnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOtkaziActionPerformed
        dispose();
    }//GEN-LAST:event_jbtnOtkaziActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(validacija()){
            Long isbn = Long.valueOf(jtxtISBN.getText());
            String naslov = jtxtNaslov.getText();
            String autor = jtxtAutor.getText();
            String izdavac = jtxtIzdavac.getText();
            String jezik = jtxtJezik.getText();
            String opis = jtxtOpis.getText();
            int brojKnjiga = Integer.valueOf(jtxtBrojStrana.getText());
            int ukupanBroj = Integer.valueOf(jtxtUkupanBrojKnjiga.getText());
            Bibliotekar b = new Bibliotekar();
            b.setKorisnickoIme("Bibliotekar1");
            try {
                Controller.getInstance().sacuvajKnjigu(new Knjiga(naslov, autor, izdavac, isbn, jezik, opis, brojKnjiga, ukupanBroj, ukupanBroj, 0, b));
                JOptionPane.showMessageDialog(rootPane, "Ubacena je nova knjiga");
                //dispose();
            } catch (SQLException ex) {
                Logger.getLogger(FKnjiga.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorAutor;
    private javax.swing.JLabel errorBrojStrana;
    private javax.swing.JLabel errorIsbn;
    private javax.swing.JLabel errorIzdavac;
    private javax.swing.JLabel errorJezik;
    private javax.swing.JLabel errorNaslov;
    private javax.swing.JLabel errorOpis;
    private javax.swing.JLabel errorUkupanBroj;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnOtkazi;
    private javax.swing.JTextField jtxtAutor;
    private javax.swing.JTextField jtxtBrojStrana;
    private javax.swing.JTextField jtxtISBN;
    private javax.swing.JTextField jtxtIzdavac;
    private javax.swing.JTextField jtxtJezik;
    private javax.swing.JTextField jtxtNaslov;
    private javax.swing.JTextArea jtxtOpis;
    private javax.swing.JTextField jtxtUkupanBrojKnjiga;
    // End of variables declaration//GEN-END:variables

    private void prepareForm() {
        setLocationRelativeTo(null);
    }

    private boolean validacija() {
        boolean pom = true;
        izbrisi();
        if(jtxtNaslov.getText().isEmpty()){
            errorNaslov.setText("Unesite naslov!");
            pom = false;
        }
        if(jtxtAutor.getText().isEmpty()){
            errorAutor.setText("Unesite autora!");
            pom = false;
        }
        if(jtxtIzdavac.getText().isEmpty()){
            errorIzdavac.setText("Unesite izdavaca!");
            pom = false;
        }
        if(jtxtISBN.getText().isEmpty()){
            errorIsbn.setText("Unesite isbn!");
            pom = false;
        }
        if(jtxtJezik.getText().isEmpty()){
            errorJezik.setText("Unesite jezik!");
            pom = false;
        }
        if(jtxtBrojStrana.getText().isEmpty()){
            errorBrojStrana.setText("Unesite broj strana!");
            pom = false;
        }
        if(jtxtUkupanBrojKnjiga.getText().isEmpty()){
            errorUkupanBroj.setText("Unesite ukupan broj primeraka!");
            pom = false;
        }
        if(jtxtOpis.getText().isEmpty()){
            errorOpis.setText("Unesite opis!");
            pom = false;
        }
        try {
            Integer.valueOf(jtxtBrojStrana.getText());
        } catch (Exception e) {
            errorBrojStrana.setText("Pogresan unos");
            pom = false;
        }
        
        try {
            Integer.valueOf(jtxtUkupanBrojKnjiga.getText());
        } catch (Exception e) {
            errorUkupanBroj.setText("Pogresan unos");
            pom = false;
        }
        
        
        
        return pom;
    }
    
    private void izbrisi(){
        errorAutor.setText("");
        errorBrojStrana.setText("");
        errorIzdavac.setText("");
        errorIsbn.setText("");
        errorJezik.setText("");
        errorNaslov.setText("");
        errorUkupanBroj.setText("");
        errorOpis.setText("");
        
        errorAutor.setForeground(Color.red);
        errorBrojStrana.setForeground(Color.red);
        errorIzdavac.setForeground(Color.red);
        errorIsbn.setForeground(Color.red);
        errorJezik.setForeground(Color.red);
        errorNaslov.setForeground(Color.red);
        errorUkupanBroj.setForeground(Color.red);
        errorOpis.setForeground(Color.red);
    }
}
