/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.form;

import controller.Controller;
import domain.Knjiga;
import domain.Korisnik;
import domain.Ocena;
import domain.Rezervacija;
import domain.StatusRezervacije;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import ui.table.model.RezervacijaTableModel;

/**
 *
 * @author Nikola
 */
public class FPretraziRezervacije extends javax.swing.JDialog {

    /**
     * Creates new form FPretraziRezervacije
     */
    public FPretraziRezervacije() {
        initComponents();

        prepareForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbtnIzaberi = new javax.swing.JButton();
        jbtnPromeniStatus = new javax.swing.JButton();
        jbtnOtkazi = new javax.swing.JButton();
        jbtnOceni = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Rezervacije"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jbtnIzaberi.setText("Izaberi");
        jbtnIzaberi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIzaberiActionPerformed(evt);
            }
        });

        jbtnPromeniStatus.setText("Promeni status");
        jbtnPromeniStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPromeniStatusActionPerformed(evt);
            }
        });

        jbtnOtkazi.setText("Otkazi");
        jbtnOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOtkaziActionPerformed(evt);
            }
        });

        jbtnOceni.setText("Oceni");
        jbtnOceni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOceniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnIzaberi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnPromeniStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnOtkazi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnOceni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnIzaberi)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnPromeniStatus)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnOceni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnOtkazi)))
                .addGap(42, 42, 42))
        );

        jLabel1.setText("Korisnik:");

        jLabel2.setText("Ulogovan Korisnik");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnIzaberiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIzaberiActionPerformed
        RezervacijaTableModel rtm = (RezervacijaTableModel) jTable1.getModel();
        int prom = jTable1.getSelectedRow();

        Rezervacija r = rtm.getRezervacije(prom);
        Controller.getInstance().getMapa().put("current_rezervacija", r);
        //Controller.getInstance().formaNovaRezervacija();
        dispose();
    }//GEN-LAST:event_jbtnIzaberiActionPerformed

    private void jbtnOceniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOceniActionPerformed
        boolean postoji = false;
        List<Ocena> lista = Controller.getInstance().vratiSveOceneDateKnjige((Knjiga) Controller.getInstance().getMapa().get("selected_knjiga"));
        for (Ocena ocena1 : lista) {
            if (ocena1.getKorisnik().getKorisnickoIme().equals(((Korisnik) Controller.getInstance().getMapa().get("active_user")).getKorisnickoIme())) {
                JOptionPane.showMessageDialog(rootPane, "Vec ste ocenili datu knjigu");
                postoji = true;
            }
        }
        if (!postoji) {
            JDialog frame;
            try {
                frame = new FOcena();
                frame.setVisible(true);
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jbtnOceniActionPerformed

    private void jbtnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOtkaziActionPerformed
        dispose();
    }//GEN-LAST:event_jbtnOtkaziActionPerformed

    private void jbtnPromeniStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPromeniStatusActionPerformed
        RezervacijaTableModel rtm = (RezervacijaTableModel) jTable1.getModel();
        int prom = jTable1.getSelectedRow();

        Rezervacija r = getSelected();
        if (r.getStatusRezervacije().equals(StatusRezervacije.aktivna)) {
            r.setStatusRezervacije(StatusRezervacije.vracena);
        } else{
            r.setStatusRezervacije(StatusRezervacije.aktivna);
        }
        rtm.alter(r, prom);
        Controller.getInstance().izmeniRezervaciju(r);
        JOptionPane.showMessageDialog(rootPane, "Promenjen je status");
    }//GEN-LAST:event_jbtnPromeniStatusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnIzaberi;
    private javax.swing.JButton jbtnOceni;
    private javax.swing.JButton jbtnOtkazi;
    private javax.swing.JButton jbtnPromeniStatus;
    // End of variables declaration//GEN-END:variables

    private void prepareForm() {
        setLocationRelativeTo(null);

        fillTable();

        jLabel2.setText(Controller.getInstance().postaviImeUsera(Controller.getInstance().getMapa().get("active_user")));
    }

    private void fillTable() {
        jTable1.setModel(new RezervacijaTableModel(Controller.getInstance().vratiRezervacije()));
    }

    private Rezervacija getSelected() {
        RezervacijaTableModel rtm = (RezervacijaTableModel) jTable1.getModel();
        int prom = jTable1.getSelectedRow();

        Rezervacija r = rtm.getRezervacije(prom);
        return r;
    }
}
